export const SITE = {
  name: "Voitov Studio",
  legalName: "ИП Войтов Никита Алексеевич",
  tagline: "Нешаблонные сайты с вау-эффектом",
  description:
    "Креативная веб-студия: лендинги, сайты услуг, айдентика и цифровые воронки для бизнеса, который хочет выглядеть сильнее конкурентов.",
  baseUrl: "https://voitov.ru",
  phone: "+7 (995) 903-91-61",
  phoneHref: "tel:+79959039161",
  secondaryPhone: null as string | null,
  secondaryPhoneHref: null as string | null,
  email: "hello@voitov.ru",
  emailHref: "mailto:hello@voitov.ru",
  workHours: "Пн–Пт, 10:00–19:00",
  address: "Москва, Научный проезд, 14А, стр. 1",
  visitNote: "Перед приездом обязательно позвоните или напишите.",
  inn: "772836163566",
  ogrn: "316774600324791",
  instagram: "https://www.instagram.com/voitov.ru/",
  facebook: "https://m.facebook.com/groups/1689374622215315",
  vk: null as string | null,
  odnoklassniki: null as string | null,
  max: "https://max.ru/",
  maxPhone: "+7 (995) 903-91-61",
  whatsapp: "https://wa.me/79959039161",
  telegram: "https://t.me/voitov23",
  spasibo: "/spasibo",
  privacy: "/privacy",
} as const;

export const NAV_LINKS = [
  { href: "/", label: "Главная" },
  { href: "/services", label: "Услуги" },
  { href: "/portfolio", label: "Работы" },
  { href: "/reviews", label: "Отзывы" },
  { href: "/faq", label: "FAQ" },
  { href: "/blog", label: "Статьи" },
  { href: "/contacts", label: "Контакты" },
] as const;

export const FOOTER_NAV = [
  { href: "/o-nas", label: "О студии" },
  { href: "/services", label: "Услуги" },
  { href: "/portfolio", label: "Работы" },
  { href: "/reviews", label: "Отзывы" },
  { href: "/faq", label: "Вопросы и ответы" },
  { href: "/news", label: "Новости" },
  { href: "/blog", label: "Статьи" },
  { href: "/contacts", label: "Контакты" },
  { href: "/privacy", label: "Политика конфиденциальности" },
] as const;
